version: '3.4'

services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /home/Tour_doan
    volumes:
      - ./:/home/Tour_doan
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
     
    networks:
      - db-network
      - poxy-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
       - 8002:80
      # - 443:443
    volumes:
      - ./://home/Tour_doan
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - poxy-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - .docker/data/db:/var/lib/mysql/
    networks:
      - db-network
  node:
    build:
      context: .docker/nodejs
      dockerfile: Dockerfile
    restart: unless-stopped


  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:80
    environment:
      UPLOAD_LIMIT: 300M
      MEMORY_LIMIT: 4096M
    depends_on:
      - db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
  poxy-network:
    driver: bridge